# Generated by Django 5.0.2 on 2024-03-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=40, null=True, unique=True),
        ),
    ]
