# Generated by Django 5.0.2 on 2024-02-26 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('duty', models.TextField()),
                ('sport_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_positions', to='team.sportactivity')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.SmallIntegerField()),
                ('image', models.ImageField(null=True, upload_to='trainer')),
                ('instagram_id', models.URLField(default='#')),
                ('twitter_id', models.URLField(default='#')),
                ('linkedin_id', models.URLField(default='#')),
                ('job_position', models.ManyToManyField(related_name='trainers', to='team.jobposition')),
            ],
        ),
    ]
