# Generated by Django 5.0.2 on 2024-02-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='instagram_id',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='linkedin_id',
            field=models.URLField(blank=True, default='#'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter_id',
            field=models.URLField(blank=True, default='#'),
        ),
    ]
