# Generated by Django 5.0.2 on 2024-02-27 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_trainer_instagram_id_alter_trainer_linkedin_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='instagram_id',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='linkedin_id',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='twitter_id',
            field=models.CharField(blank=True, default='#', max_length=300),
        ),
    ]
