# Generated by Django 5.0.2 on 2024-02-27 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
