# Generated by Django 5.0.2 on 2024-02-27 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_trainercomment_published_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainercomment',
            name='published_at',
        ),
    ]
