# Generated by Django 5.0.2 on 2024-02-27 19:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_remove_trainercomment_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainercomment',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
