# Generated by Django 5.0.2 on 2024-03-03 17:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_category_options_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomment',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
