# Generated by Django 5.0.2 on 2024-02-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='held_class',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='trainer',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='week_day',
        ),
        migrations.DeleteModel(
            name='HeldClass',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.DeleteModel(
            name='WeekDay',
        ),
    ]
