# Generated by Django 5.0.2 on 2024-02-27 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0002_remove_schedule_held_class_remove_schedule_trainer_and_more'),
        ('team', '0003_alter_trainer_instagram_id_alter_trainer_linkedin_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeldClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('held_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.heldclass')),
                ('trainer', models.ManyToManyField(related_name='schedules', to='team.trainer')),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='schedule.weekday')),
            ],
        ),
    ]
